modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
displayName = "${mod_name}"
authors = "${mod_authors}"
displayURL = "https://www.curseforge.com/projects/242995/"
logoFile = "icon.png"

description = '''${mod_description}'''