modLoader = "javafml"
loaderVersion = "[36,)"

license = "All rights reserved"

[[mods]]

modId = "custom_crosshair_mod"

version = "1.3.4-forge"

displayName = "Custom Crosshair Mod"

displayURL = "https://www.curseforge.com/projects/242995/"

logoFile = "icon.png"

authors = "Sparkless101"

description = '''
A dynamic and customisable crosshair.
'''